- hosts: localhost
  gather_facts: yes
  become: true
  tasks:
    - name: Creation of network
      docker_network:
        name: networkn
        state: present

    - name: Backend - MySQL container
      docker_container:
        name: db
        image: mysql:5.7
        ports:
          - "3306:3306"
        state: present
        networks:
          - name: networkn
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: finance
          MYSQL_USER: admin1
          MYSQL_PASSWORD: admin1
        restart_policy: always

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        delay: 10  # Wait 10 seconds before starting
        timeout: 300  # Wait up to 5 minutes for MySQL to be ready

    - name: Frontend - Application container
      docker_container:
        name: frontend
        image: problemsetters/801133-ansible:latest
        networks:
          - name: networkn
        ports:
          - "8000:8081"
        state: present
        restart_policy: always
        env:
          DATABASE_HOST: db
          DATABASE_PORT: "3306"
          DATABASE_USER: admin1
          DATABASE_PASSWORD: admin1
          DATABASE_NAME: finance

